### ISSUE TITLE
why the non-Java frames preceding the Java frames not show ?

### ISSUE THREAD

**Issue by ygdyang** [jvm-profiling-tools/async-profiler#110]
I have read the "Restrictions/Limitations" in readme, it said that "You will not see the non-Java frames preceding the Java frames on the stack". 
I am curious about that，why this frame is not showed. I have read the function "getCallChain" in perfEvents_linux.cpp, It use PerfEvent to get the native stack, while the "perf-map-agent"  tool (https://github.com/jvm-profiling-tools/perf-map-agent) which based on perf can show these frames(such as start_threa, JavaMain, ...) .

**Comment by nitsanw** [comment]
async-profiler take a mixed approach where the perf stack is pasted on top of the Java stack. This means that perf does not walk any frames between the top Java frame and the bottom of the stack. Any intermediate/preceding native frames are thus invisible.

**Comment by nitsanw** [comment]
See #66

**Comment by ygdyang** [comment]
I thought the perf statck should contain every native frames (written by c/c++), which including start_thread, JavaMain. but actually, It seems not. I fell confused about it。

**Comment by apangin** [comment]
By design, async-profiler uses only the top of perf_events stack until the first Java frame. Everything below the first Java frame is obtained from AsyncGetCallTrace. Then these two parts are merged together. 

![async-profiler](https://user-images.githubusercontent.com/1749416/39128583-cd5af97e-4710-11e8-8bfc-93ec7f6c7251.png)

This approach allows to get mixed call stack without facing the following disadvantages of pure perf_map_agent:
- It requires `-XX:+PreserveFramePointer` option which imposes certain performance overhead. Without this option it won't be possible to walk through Java frames.
- It works only on JDK 8u60+
- It does not show interpreted methods
- The stack depth is limited by 127 (unless tuned in kernel)
- It produces large amount of temporary data on disk.

**Comment by apangin** [comment]
I will consider the requirement to show native stack below Java frames when implementing #66.

**Comment by ygdyang** [comment]
Thanks a lot for your explanation, but I still can not understand why the native stack,  which got from perf_events, does not contain the `start_thread`, `JavaMain` frames. Maybe I'm not familiar with perf_events.

**Comment by apangin** [comment]
@ygdyang If there is no `-XX:+PreserveFramePointer` JVM flag, kernel gets stuck at the first Java frame, since JVM does not maintain typical frame-linking structure when calling Java methods.

With `-XX:+PreserveFramePointer` flag JVM links frames as perf_events expect, so the stack *will cointain* `start_thread` etc. But async-profiler does not make use of it.

**Comment by ygdyang** [comment]
@apangin That is exactly what I was confused about before! Thank you very much!!

Here comes another question, Is it possible that a java project's stack looks like these:
```
native frames3
java frames2
native frames2
java frames1
native frames1
```
I know It may be quite normal in some python project. But I'm not sure If it's the same for java project, If It's possible, we may miss the `native frames2` ? which may be useful, as it may not just the `start_thread`, `JavaMain` etc.
And even the `java frames1` will be missing?

**Comment by apangin** [comment]
Yes, native code may do Java upcalls, and the stack will look like in your example.
With current approach async-profiler will show all Java frames and top native frames:
```
native frames3
java frames2
java frames1
```

**Comment by ygdyang** [comment]
OK, I got it.
Thanks a lot again!
