### ISSUE TITLE
By tracking overall CPU usage for process profiler could detect sample collections irregularities

### ISSUE THREAD

**Issue by nitsanw** [jvm-profiling-tools/async-profiler#141]
This is a purely defensive measure but might provide interesting insights. The idea being that if e.g. process 1234 is reporting usage of 1s of CPU and we are sampling at a 100 frequancy we should have 100 samples. It is probably fine for us to observe some irregularities here, but I would think the information can help identify faults in the assumed behaviour of underlying OS facility (perf on Linux). The functionality could be used via performance counters to similarly make observations on other event types.

**Comment by apangin** [comment]
Since version 2.0, async-profiler records `jdk.CPULoad` JFR event every second, which includes

- the process' user and system CPU load;
- overall machine CPU load in %.

JDK Mission Control and IntelliJ IDEA use this information to display nice CPU usage graphs. Other tools may parse JFR output to analyze this information somehow, but I guess this is beyond async-profiler responsibilities.

**Comment by nitsanw** [comment]
Thanks!

**Comment by nitsanw** [comment]
The way CPU load is recorded by the JVM is confusing:
- Process CPU% (of machine) + system CPU%(of machine)
- Thread CPU% (of machine)
This makes sense only if you know the number of available cores.

**Comment by apangin** [comment]
Good point. JFR has `jdk.CPUInformation` event - I'll make async-profiler record that too.

**Comment by apangin** [comment]
Forgot to mention, I've added `jdk.CPUInformation` event.
