### ISSUE TITLE
undefined symbol: clock_gettime

### ISSUE THREAD

**Issue by whitelilis** [jvm-profiling-tools/async-profiler#145]
when I run it with agent mode, it says:
java: symbol lookup error: /var/lib/hadoop-yarn/ap/build/libasyncProfiler.so: undefined symbol: clock_gettime

java version : 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

kernel version: 2.6.32-504.el6.x86_64

**Comment by apangin** [comment]
I guess this is because `clock_gettime` requires linking to `librt` with older glibc.

Try this version of [libasyncProfiler.so](https://github.com/jvm-profiling-tools/async-profiler/files/2205630/libasyncProfiler.so.zip) and tell if it works.

However, I wouldn't be optimistic, since Linux kernel 2.6.32 is a way too old. I remember seeing bugs with `perf_event_open` API on Linux 2.6.34. It worked for me on 2.6.39.

Anyway, try the attached version of the agent. I'll be glad to hear any feedback, either positive or negative.

**Comment by apangin** [comment]
I've removed usages of `clock_gettime` completely. There should not be such error anymore.
Let me know if profiler works on your system.
