### ISSUE TITLE
No java stacks under Graal compiler

### ISSUE THREAD

**Issue by justinas-dabravolskas** [jvm-profiling-tools/async-profiler#181]
Async-profiler v1.4 doesn't collect application java stacks while profiling cpu of JVM running with Graal compiler. Stacks for Graal itself and GC are there, but java.lang.Thread.run is not.
JDK 10  with -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler

**Comment by apangin** [comment]
This is a problem of HotSpot AsyncGetCallTrace API. It does not work for methods compiled with Graal. Unfortunately, there is no a simple workaround in async-profiler. I added this issue to the backlog of #66.

**Comment by apangin** [comment]
As far as I see, the problem has been fixed on JDK side.
OpenJDK 15 shows Graal stack traces normally. So does the current version of GraalVM (20.3.0).
Closing the issue, as there is nothing to do from async-profiler side.

**Comment by bric3** [comment]
I can confirm it is fixed in OpenJDK 15.0.2. However it is not yet fixed in JDK 11.0.10.

For reference note that profiling during application bootstrap, one is likely one see a lot of compilation frames (graal), for example.

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/803621/111907647-8f3ea500-8a56-11eb-848a-50036b3b52c7.png">

If profiling is started late and the application is hot enough one can spot the application frames.

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/803621/111908116-41c33780-8a58-11eb-946f-11357859e12b.png">
