### ISSUE TITLE
OS crash while profiling Jboss application on redhat 6.0

### ISSUE THREAD

**Issue by bbccaaac** [jvm-profiling-tools/async-profiler#195]
Some time ago OS crashed when I ran './profiler.sh -d 30 -f /mnt/async-profiler/profile.svg 1681'. Screen showed as follows:
![image](https://user-images.githubusercontent.com/11207733/51515892-4ed04600-1e50-11e9-8eca-c86802412cfe.png)

Use strace in that pid of jboss app as follows:
[root@redh ~]# strace -p 1636
Process 1636 attached - interrupt to quit
futex(0x7f743eb749e0, FUTEX_WAIT, 1637, NULL) = ? ERESTARTSYS (To be restarted)
--- SIGQUIT (Quit) @ 0 (0) ---
futex(0x7f743f9ae240, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn(0x7f743f9ae240)            = 202
futex(0x7f743eb749e0, FUTEX_WAIT, 1637, NULL

but I use it profiling other application or using './profiler.sh -d 30 -e itimer -f /mnt/async-profiler/profile.svg 1681' is normal.

**Comment by apangin** [comment]
I guess the reason could be an old kernel version. What does `uname -a` say?

**Comment by bbccaaac** [comment]
The kernel version of my test OS is:
[root@redh ~]# uname -a
Linux redh 2.6.32-71.el6.x86_64 #1 SMP Wed Sep 1 01:33:01 EDT 2010 x86_64 x86_64 x86_64 GNU/Linux

Maybe you are right. when I tested it on Tomcat, OS also crash. 

I test it on redhat 6.5. It is OK. 
[root@Janefu async-profiler]# ./profiler.sh -d 10 -f /mnt/async-profiler/a.svg 2094
[root@Janefu async-profiler]# uname -a
Linux Janefu 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by apangin** [comment]
Ah, I see. 2.6.32 is indeed too old. It is the first version where `perf_event_open` API appeared.
From my observation, `perf_event_open` became more or less stable since 2.6.39.
The BUGS secion in the [manual](http://man7.org/linux/man-pages/man2/perf_event_open.2.html) also suggests the API was unstable before 2.6.39.

So, you need either to upgrade kernel or to use `-e itimer` mode which does not rely on `perf_event_open`.

Meanwhile I'll add a version check that will automatically fallback to `itimer` engine whenever an old kernel version is detected.

**Comment by bbccaaac** [comment]
I see.Thanks a lot.
