### ISSUE TITLE
thread-smoke-test.sh doesn't always pass

### ISSUE THREAD

**Issue by jchipmunk** [jvm-profiling-tools/async-profiler#196]
Hi,

`thread-smoke-test.sh` sometime fails in Alpine Linux:
```
test/thread-smoke-test.sh
+ '[' -z /usr/lib/jvm/java-1.8-openjdk ']'
++ dirname test/thread-smoke-test.sh
+ cd test
+ '[' ThreadsTarget.class -ot ThreadsTarget.java ']'
+ /usr/lib/jvm/java-1.8-openjdk/bin/javac ThreadsTarget.java
+ FILENAME=/tmp/java.trace
+ /usr/lib/jvm/java-1.8-openjdk/bin/java -agentpath:../build/libasyncProfiler.so=start,collapsed,threads,file=/tmp/java.trace ThreadsTarget
+ assert_string '\[ThreadEarlyEnd tid=[0-9]\+\];.*ThreadsTarget.methodForThreadEarlyEnd;.*'
+ grep -q '\[ThreadEarlyEnd tid=[0-9]\+\];.*ThreadsTarget.methodForThreadEarlyEnd;.*' /tmp/java.trace
+ exit 1
make: *** [Makefile:58: test] Error 1
```
where `/tmp/java.trace` file has the following content:
```
$ cat /tmp/java.trace
[RenamedThread tid=4158];java/lang/Thread.run;clock_gettime 1
[RenamedThread tid=4158];java/lang/Thread.run;gettimeofday 17
[RenamedThread tid=4158];__vdso_clock_gettime 1
[ThreadEarlyEnd tid=4157];java/lang/Thread.run;gettimeofday 1
[ThreadEarlyEnd tid=4157];clock_gettime;__vdso_clock_gettime 1
[ThreadEarlyEnd tid=4157];clock_gettime;__vdso_clock_gettime;[vdso] 5
[RenamedThread tid=4158];clock_gettime 2
[RenamedThread tid=4158];clock_gettime;__vdso_clock_gettime;[vdso] 22
[RenamedThread tid=4158];java/lang/Thread.run;ThreadsTarget$2.run;ThreadsTarget.methodForRenamedThread 1
[RenamedThread tid=4158];java/lang/Thread.run;os::javaTimeMillis() 22
[RenamedThread tid=4158];clock_gettime;__vdso_clock_gettime 18
[ThreadEarlyEnd tid=4157];clock_gettime;[vdso] 1
[ThreadEarlyEnd tid=4157];java/lang/Thread.run;os::javaTimeMillis() 6
```

CI failed build: https://travis-ci.org/alpinelinux/aports/builds/477555640?utm_source=github_status&utm_medium=notification

**Comment by apangin** [comment]
Thank you for the report.
I'll check whether it is a problem of the profiler or of the test.

**Comment by apangin** [comment]
The problem is `ThreadsTarget` does nothing but calling `System.currentTimeMillis()` in a loop. However, `currentTimeMillis` is a really bad method for stack walking. It is JVM intrinsic which is translated to a raw call to `os::javaTimeMillis()` which in turn calls `gettimeofday` from [`vdso`](http://man7.org/linux/man-pages/man7/vdso.7.html).

It turns out that on Alpine Linux neither JDK nor vDSO is compiled with `no-omit-frame-pointer` option. This makes practically impossible to recover last Java frame while executing `System.currentTimeMillis()`, unless the caller method is interpreted. That's why profiler output contains truncated stack traces.

async-profiler can hardly do anything to overcome the problem. So I'll just modify the test to do some real computation besides calling `System.currentTimeMillis()`.

**Comment by jchipmunk** [comment]
I checked it, thread-smoke-test.sh passed. Thank you!
