### ISSUE TITLE
[Feature request] Add support for DWARF stack unwinding to show inlined native frames

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#215]
On recent(-ish) versions of Fedora/RHEL/CentOS perf uses the elfutils/libdw unwinder instead of
libunwind since it is faster and more reliable on all supported
architectures: supporting stack unwinding using DWARF would be great to allow a better observability of the native space, given that inlined native frame are not available while using commong FP stack walking.

**Comment by apangin** [comment]
I looked at libdw, but did not see how it could be easily integrated into async-profiler.
The main problem is that the profiler can currently use only async signal safe API for stack walking.

However, I'll leave this issue open in case I decide to revise how async-profiler process stack traces (i.e. switch to offline processing).

**Comment by franz1981** [comment]
I can write again to Jiri Olsa, dev of libdw, to ask for some help about it...maybe I will get some good hints on how to integrate it and will send a PR, but many thanks to have taken a look!!!

**Comment by apangin** [comment]
I spent some more time researching the topic, and came up with two findings: a good one and a bad one.

The bad one is that it doesn't look feasible to do DWARF-based unwinding on the fly. DWARF unwinding is really expensive both in computation and in memory used. While it's not usually a problem to get a stack trace during debugging, interpreting DWARF information during profiling will cause too much overhead. Furthermore, in async-profiler's case, stack traces are collected inside a signal handler, that incurs strict limitations on what can be done: e.g. no memory allocation, no locks etc.

There is a recent study [[1]](https://fzn.fr/projects/frdwarf/frdwarf-oopsla19.pdf) on improving DWARF unwinding performance by an order of magnitude using precompiled unwind tables. Sounds cool, except that implementing this approach in async-profiler would mean creating a specialized JIT compiler for unwind tables. This task alone is bigger than the rest of the profiler :) That's going to be too much effort for a *Java* profiler.

But I also have a good news for you.

Modern Intel CPUs can profile branch instructions, including `call`s and `ret`s, and store their source and destination addresses (Last Branch Records) in hardware registers. Starting from Haswell, CPU can match these addresses to form a branch stack. This branch stack will be effectively a call chain automatically collected by the hardware.

What makes LBR call chain especially useful is that it works even without frame pointers. `perf` has supported LBR since Linux 4.1, and now I've added LBR call chain support to async-profiler.

The new option is `--cstack lbr`. It works only with hardware events like `-e cycles` (`instructions`, `cache-misses` etc.)

The maximum call chain depth is 32 (hardware limit). LBR stacks are not always complete or accurate, but they still appear much more helpful comparing to fp-based stack waling, when a native library is compiled with omitted frame pointers.

Here is an example of a traditionally collected profile:

![flame-fp](https://user-images.githubusercontent.com/1749416/79919457-1e9e9b00-8437-11ea-87b1-fe230fdf69ae.png)

and the same application profiled with `--cstack lbr`:

![flame-lbr](https://user-images.githubusercontent.com/1749416/79919499-383fe280-8437-11ea-8f7a-203a84dd5ad7.png)

**Comment by apangin** [comment]
Taking the above into account, there are no plans to support DWARF in async-profiler.
LBR stack unwinding is a viable alternative.

**Comment by apangin** [comment]
I had to return to the problem of native stack unwinding in the context of another task.

DWARF is indeed a complex format; it's not just a *format*, but a Turing-complete virtual machine with its own bytecode, computation stack, etc. Fortunately, gcc and clang typically use only a small subset of DWARF functionality to encode unwind info for normal C/C++ routines. Furthermore, in most cases we don't need to decode information about registers other than the stack pointer (RSP) and the frame pointer (RBP).

So I came up with a solution that parses a small subset of DWARF and builds a lookup table. It's not a complete DWARF interpreter, but it helps to unwind the majority of C/C++ frames on linux_x64. Haven't implemented this for other platforms yet.

DWARF unwinding *do* requires extra memory (e.g. the lookup table for `libjvm.so` is about 2MB), and is slower than the traditional FP-based stack walker, but it's still fast enough for on-the-fly unwinding (I was able to make it signal safe).

I invite you to give it a try and provide the feedback. The code is available in [`dwarf`](https://github.com/jvm-profiling-tools/async-profiler/tree/dwarf) branch.  
Use `--cstack dwarf` option to enable DWARF unwinding.

**Comment by apangin** [comment]
E.g. the profile collected with a traditional FP-based stack walker:

![fp](https://user-images.githubusercontent.com/1749416/142681584-03a633d6-c6c7-479a-a8e0-da400b15c509.png)

And the same profile collected with `--cstack dwarf`:

![dwarf](https://user-images.githubusercontent.com/1749416/142681619-865e453c-91d7-431a-b286-585fdf23403a.png)

**Comment by franz1981** [comment]
Great! I have taken a look at the code yesterday ;)
I will try asap and I can already see how much more detailed it looks on native side (including GC frames too)

**Comment by Jongy** [comment]
> but it's still fast enough for on-the-fly unwinding (I was able to make it signal safe).

Very impressive @apangin !

**Comment by krzysztofslusarski** [comment]
Thank you @apangin
