### ISSUE TITLE
Calls Missing in Simple Trace

### ISSUE THREAD

**Issue by DaGeRe** [jvm-profiling-tools/async-profiler#223]
When I execute simple workloads, some calls seem to be missing or even wrong in the stacks. For example, considering the class
```
class Main {
	public static void main(String args[]) {
		for (int i = 0; i < 1000000; i++) {
			for (int j = 0; j < 5000; j++) {
				StringBuilder builder = stringAddition(j);
				if (builder.length() == 3) {
					System.exit(-1);
				}
			}
		}
	}

	public static StringBuilder stringAddition(int j) {
		StringBuilder builder = new StringBuilder();
		builder.append("Hello world");
		builder.append("hello");
		return builder;
	}
}
```

If I compile it with OpenJDK 11.0.3 on 64 Bit Ubuntu 18.04 and run it with 
`java -agentpath:$(pwd)/../async-profiler/build/libasyncProfiler.so=start,summary,traces=5,flat=10,file=mainprofile.txt -XX:+UnlockDiagnosticVMOptions -XX:+PreserveFramePointer -XX:+DebugNonSafepoints Main`
the traces contain entries like

> --- 14120248769 ns (56.39%), 1412 samples
>   [ 0] jbyte_disjoint_arraycopy
>   [ 1] Main.main
> 

Obviously, the Array copying was not invoked by Main, but (probably) by 'String.getBytes' or by 'AbstractStringBuffer.ensureCapacityInternal'. These entries are missing.

Stacks are only collected at safepoints, and therefore not always are exact. Nevertheless, if a trace is collected, shouldn't it be correct? Or is this an example of missing accuracy from #66?

Is there some solution / workaround, which could help me to get full traces for debugging purpose (at the cost of accuracy and performance)?

**Comment by apangin** [comment]
This is a known problem of HotSpot AsyncGetCallTrace API.
I've submitted the bug [JDK-8178287](https://bugs.openjdk.java.net/browse/JDK-8178287) with the detailed analysis more than 2 years ago, but unfortunately there has been no progress on it.

In short, HotSpot cannot get stack traces at all while in the middle of `System.arraycopy`. This is a JVM fault, not the profiler's. For example, other tools based on AsyncGetCallTrace (e.g. honest-profiler or lightweight-java-profiler) will show none of these stack traces at all, returning `AGCT.UnknownJavaErr5` error instead.

In contrast, async-profiler does its best to workaround this bug by popping the non-walkable stack frame off and trying to recover the rest of the stack trace. This is exactly what happens in your example, and that's why you see truncated stack traces. In fact, there is only one frame missing, but since several Java methods can be inlined into one frame, this may look as if several (inlined) methods are absent.

If you run Java with `-XX:MaxInlineLevel=0` or `-XX:TieredStopAtLevel=1`, the stack traces will be certainly better, but the performance impact can be very big.

**Comment by sattishv** [comment]
Hi ,

You have mentioned that this issue persists even with honest-profiler. How about with Java Mission Control because JMC claim that with this flag  -XX:+DebugNonSafepoints we can get accurate results.
and I percept DebugNonSafepoints will in turn invoke AGCT to get accuracy. Is that right. Could you please clarify on this.

**Comment by apangin** [comment]
@sattishv `-XX:+DebugNonSafepoints` option improves stack traces both for async-profiler and JMC; this is a highly recommended option for profiling. Also, if async-profiler is enabled via `-agentpath`, it turns on this option automatically.

JMC does not use AsyncGetCallTrace. Instead, when Flight Recorder is on, HotSpot collects stack trace samples through its own internal interface. However, the mechanism is almost the same in both cases. And yes, JMC also suffers from the above problems. If you run any of examples from [JDK-8178287](https://bugs.openjdk.java.net/browse/JDK-8178287) with async-profiler and then with Flight Recorder, you'll see that JMC collects much less samples (it silently ignores events when it fails to traverse Java stack).

**Comment by sattishv** [comment]
Thanks a lot for the response. I have created one more ticket on the same front . Could you please take a look.
