### ISSUE TITLE
stop does not return

### ISSUE THREAD

**Issue by computinglife** [jvm-profiling-tools/async-profiler#224]
When i run the asyn-profiler with -e cpu i am not able to get it to return any data after i invoke profiler.sh with the stop argument. 

It works fine when the system is not too busy. But if i try to capture data when the process is busy, i dont see errors, but the call does not return. The process does not consume too much CPU either. 

I tried to strace the jattach call on stop which is left hanging - i can see that its stuck on a read call (file descriptor count 3 - which is  3 -> socket:[14138219] as reported from proc) but thats pretty much it. 

I can also see a few errors messages "perf_event mmap failed: Operation not permitted" initially but it does not repeat unlike where the kernel settings are not changed. 

Would appreciate any help on this. Is there a limit on the no of samples that can be collected? 

Thanks

process is 32 bit
Kernel = Centos 7 = 3.10.0-862.11.6.2.el7.x86_64
 perf rpm =  perf-3.10.0-693.el7.x86_64
Java version = java version "1.7.0_191"

Perf settings applied : 

echo 1000000 >  /proc/sys/kernel/perf_event_max_sample_rate
echo 50 > /proc/sys/kernel/perf_cpu_time_max_percent
echo 0 > /proc/sys/kernel/kptr_restrict
echo 1 > /proc/sys/kernel/perf_event_paranoid

**Comment by apangin** [comment]
There was a report on a similar issue - #221. Still not sure about the reasons :(
Looks like `perf_event_open` syscall becomes slow in some cases, so that profiler's `start` command does not complete in a reasonable period of time. Then `stop` command hangs as it waits AttachListener to complete a previous command.

Does your application run many threads under load? (I mean, thousands). How long does the profiling session run?

Try

1. increasing profiling interval `-i`
2. `-e itimer` mode

I guess `itimer` should help, since the problem seems to be hidden somewhere inside `perf_event_open`.

Also `perf_event mmap failed: Operation not permitted` message means that `perf_event_mlock_kb` has exceeded. It's not a fatal error, but it's better to increase the limit as described [here](https://github.com/jvm-profiling-tools/async-profiler/#restrictionslimitations).

**Comment by computinglife** [comment]
I have moved to later version of JVM and 64 bit in the hope i will be running something more closer to whats being used commonly.
