### ISSUE TITLE
Measure number of allocations

### ISSUE THREAD

**Issue by estaban** [jvm-profiling-tools/async-profiler#228]
It would be great to add an option to record allocation events (each time on object is created). Currently, allocation profiling is biased towards big allocations because one event represent an allocation every n kB. The object creation rate also plays a significant role in the durations of the GC STW pauses, and would be very useful to analyze through a flamegraph.

**Comment by apangin** [comment]
Measuring *every* allocation is not possible with a sampling profiler.

There are other (instrumenting) profilers capable of doint this, but due to instrumentation overhead they can slow down an application by an order of magnitude. The overhead of async-profiler is typically less than 3%.

It's true that a 400-byte object will be sampled roughly ten times more often than a 40-byte object of the same allocation rate. On the other hand, the allocation of a larger object will cause a GC cycle proportionally more often. So, in terms of GC pressure, the sampling profiler gives an objective picture.

Since async-profiler aims at low overhead scenarios sutiable for production use, there are no plans to track every object allocation.

As a workaround, you can use the following JVM options to maximize the sampling rate

    -XX:MinTLABSize=1 -XX:TLABSize=1 -XX:-ResizeTLAB

But be aware of the huge performance impact the options may have.

**Comment by jesperpedersen** [comment]
@estaban You can see if https://github.com/jesperpedersen/javamemflame works for you -- Java 11+ though

**Comment by apangin** [comment]
@jesperpedersen Isn't javamemflame based on JFR API? In this case I expect it to have exactly the same quality of allocation profiling, since async-profiler uses the similar sampling technique as JFR, except that it works with JDK 7+ without extra JVM options.

**Comment by jesperpedersen** [comment]
@apangin Yes to JFR. Good to know :)

**Comment by estaban** [comment]
@apangin  The point is not to measure _every_ allocation, but to sample allocations based on the number of allocations, and not on the allocated size. Would it be possible to have a sampling parameter that would record the allocation event and the stack frame at this event every n allocations? That would still keep async-profiler low overhead.

I agree that the frequency of the young GC pauses is more or less proportional with the allocation rate, which async-profiler currently samples very well, but AFAIK the duration of the GC pauses is very much influenced by the number of created references, which would be nice to have insight on from async-profiler.

**Comment by aalexand** [comment]
One technique employed by the sampling heap profiler in tcmalloc, Go runtime and https://github.com/v8/sampling-heap-profiler is setting the sampling byte mark by drawing a sample from Poisson distribution and mark those allocation to be sampled that cross the mark. See e.g. https://github.com/golang/go/blob/80f9d32438b85d03ea0310b67411e41619d4066b/src/runtime/malloc.go#L1173.

The sampled counts then need to be unsampled, but the advantage of this is that the sampling is not biased towards large objects and the allocation counts are unbiased as well (assuming enough samples overall).

**Comment by apangin** [comment]
@estaban I understand what you mean and agree that this might be useful in some cases. Unfortunately, HotSpot does not track the number of allocations, and I don't see how to achieve this without changing the HotSpot code or without a considerable overhead.
One possible approach is proposed above. Other ways are turning off TLAB allocations at all (e.g. with `-XX:+DTraceAllocProbes`) or instrumenting allocation bytecodes. Neither of them is low-overhead though.
