### ISSUE TITLE
Java jni call unknown function name

### ISSUE THREAD

**Issue by MacChen01** [jvm-profiling-tools/async-profiler#233]
Use it to profile hadoop-3.1.1 terasort's function, can't get jni function name, show [unknown] info.

![jni_unknown_name](https://user-images.githubusercontent.com/11262916/62603399-65d81080-b928-11e9-9192-b5547e2da48c.png)

**Comment by apangin** [comment]
It seems like a native library was loaded *after* the profiling had started.

async-profiler loads symbols beforehand, so that it could find the native functions on the fly inside the signal handler.

I have ideas how to improve that, but this may take time. Meanwhile I suggest just to repeat profiling after the library is loaded, or preload it manually with `System.loadLibrary`.

**Comment by chenqiang2080** [comment]
yes, native library was loaded after the profiling had started.
The native library was loaded by the hadoop program, it will lost part of function info when  repeat profiling after the library is loaded.

**Comment by MacChen01** [comment]
@apangin _I suggest just to repeat profiling after the library is loaded, or preload it manually with System.loadLibrary._ These methods don't work.

**Comment by apangin** [comment]
I committed the fix. Now async-profiler parses symbols of the libraries loaded after profiling has started.
