### ISSUE TITLE
Simplify recursive call traces in flamegraph

### ISSUE THREAD

**Issue by zolstein** [jvm-profiling-tools/async-profiler#234]
If a function calls itself recursively (directly or indirectly) profiling can produce a flame graph with many nested frames describing the same work separately. This makes quantifying the work done in these functions difficult, because the time accounting gets spread over many calls. Combining these into the same function may produce more useful output. I propose preprocessing stack traces to remove cycles before generating the flame graph.

**Comment by apangin** [comment]
Thank you for the feedback.
Using built-in FlameGraph Search capability allows to highlight a method in all contexts and show the total accumulated percentage.
If you have a better idea on how to display the recursive calls, please provide an example (illustrated if possible). Why I am asking - because I personally have never experienced problems with recursive calls in current implementation, and I'm not sure how to improve the graph without losing the details that current implementation provides.
