### ISSUE TITLE
Sum of percentage is not equal to 100% for allocation profiling

### ISSUE THREAD

**Issue by RoySunnySean007** [jvm-profiling-tools/async-profiler#261]
Dear Async profiler experts,

The following is my allocation profiling output result, two questions:
1. Why we will have 40% skipped?
2. I am curious why Sum of percentage is far less than 100%.

I use ./profiler.sh -g -b 5000000000 -e alloc <java pid> to do allocation profiling.
And TLAB size is 10: -XX:MinTLABSize=10,-XX:TLABSize=10,-XX:-ResizeTLAB

Really appreciate ur great help in advance!

--- Execution profile ---
Total samples       : 9330021
skipped             : 4180503 (44.81%)

Frame buffer usage  : 0.347527%

--- 6366272 bytes (1.94%), 107685 samples
--- 6033888 bytes (1.83%), 107748 samples
--- 5426112 bytes (1.65%), 330 samples
--- 5179056 bytes (1.57%), 107897 samples
--- 4834000 bytes (1.47%), 296 samples
--- 4001368 bytes (1.22%), 71453 samples
--- 3778008 bytes (1.15%), 107535 samples
--- 3743368 bytes (1.14%), 35994 samples
--- 3431584 bytes (1.04%), 107237 samples
--- 3039296 bytes (0.92%), 47489 samples
--- 2999488 bytes (0.91%), 46867 samples
--- 2938440 bytes (0.89%), 297 samples
--- 2857760 bytes (0.87%), 35722 samples
--- 2820928 bytes (0.86%), 44077 samples
--- 2782064 bytes (0.85%), 272 samples
--- 2667728 bytes (0.81%), 315 samples
--- 2588184 bytes (0.79%), 35947 samples
--- 2578104 bytes (0.78%), 107421 samples
--- 2538360 bytes (0.77%), 155 samples
--- 2523944 bytes (0.77%), 318 samples
--- 2302016 bytes (0.70%), 71938 samples
--- 2251288 bytes (0.68%), 137 samples
--- 2153616 bytes (0.65%), 44867 samples
--- 2136768 bytes (0.65%), 33387 samples
--- 2134720 bytes (0.65%), 33355 samples
--- 2075680 bytes (0.63%), 51892 samples
--- 2060160 bytes (0.63%), 51504 samples
--- 1949080 bytes (0.59%), 34805 samples
--- 1895320 bytes (0.58%), 47383 samples
omit several lines whose % of samples is far less than 0.6%

Thanks,
Roy

**Comment by apangin** [comment]
> Why we will have 40% skipped?

You've set extreme TLAB settings. This means, almost every allocation is sampled. JVM is just too busy with sampling and it can hardly do anything else useful.

In order to prevent the situation when the application threads are blocked for a long time waiting the other threads to process stack traces, async-profiler simply skips a sample if it cannot immediately acquire a lock.

In short, there are too many simultaneous allocations being recorded. This creates a huge overhead. I suggest to increate TLAB size.

> I am curious why Sum of percentage is far less than 100%.

By default, only top 200 traces are shown in the text report.  
You may increase the number with `-o traces=10000` or choose a different output format.

**Comment by RoySunnySean007** [comment]
Dear @apangin ,

Really appreciate ur quick reply!

>>>In order to prevent the situation when the application threads are blocked for a long time waiting the other threads to process stack traces, async-profiler simply skips a sample if it cannot immediately acquire a lock.

[Roy] 1. Could u please kindly elaborate the lock? i.e, how does async-profiler work to get stack trace?
2. Regarding TLAB size, do u have any recommendation for async allocation profiling? 

>>>By default, only top 200 traces are shown in the text report.

[Roy] Thanks for ur notes! In my case, top trace's percentage is only 1.94%, bottom trace's percentage is less than 0.58%, does it mean that it could have millions or billions of traces whose percentage is less than 0.58%?

Thanks,
Roy

**Comment by apangin** [comment]
> Regarding TLAB size, do u have any recommendation for async allocation profiling?

Just remove all TLAB-related JVM options. Defaults should be OK in most cases. Reducing TLAB size in production is discouraged, as it may have negative performance impact.

> does it mean that it could have millions or billions of traces whose percentage is less than 0.58%

Not millions, but several thousands are quite probable. So many different allocation stack traces are also likely to be the consequence of the extreme TLAB settings.

**Comment by RoySunnySean007** [comment]
Thanks @apangin !

>>>So many different allocation stack traces are also likely to be the consequence of the extreme TLAB settings.
hmm, do u mean the root cause of so many different allocation stack traces may be caused by extreme TLAB settings? Could u please kindly elaborate it? Thanks in advance!

Thanks,
Roy

**Comment by apangin** [comment]
I can't know for sure without seeing your particular application and the environment, but there is a *high chance* that the problem is caused by custom TLAB options. The "normal" TLAB size is usually somewhere between hundreds KB and several MB. Making TLAB size 10 bytes effectively means turning off TLAB entirely. This makes *all* allocations go the slow path. Allocation sampling events will then occur ~10000 times more frequently than usual. Of course, this may have huge performance impact and cause high contention in the allocation sampler.

**Comment by RoySunnySean007** [comment]
Thanks @apangin for ur clear explanation!
