### ISSUE TITLE
[Question] How to install openjdk debug info on Fedora, Oracle Linux, Red Hat Enterprise Linux, etc?

### ISSUE THREAD

**Issue by RoySunnySean007** [jvm-profiling-tools/async-profiler#264]
Dear async profiler experts,

I install all related open jdk in amazon linux, but when I use async profiler to do allocation profiling, it still report "No AllocTracer symbols found. Are JDK debug symbols installed?", do u have any idea?

Thanks in advance!

```
copy-jdk-configs.noarch               3.3-10.amzn2                   @amzn2-core
java-1.8.0-openjdk.x86_64             1:1.8.0.222.b10-0.amzn2.0.1    @amzn2-core
java-1.8.0-openjdk-debug.x86_64       1:1.8.0.222.b10-0.amzn2.0.1    @amzn2-core
java-1.8.0-openjdk-devel.x86_64       1:1.8.0.222.b10-0.amzn2.0.1    @amzn2-core
java-1.8.0-openjdk-devel-debug.x86_64 1:1.8.0.222.b10-0.amzn2.0.1    @amzn2-core
java-1.8.0-openjdk-headless.x86_64    1:1.8.0.222.b10-0.amzn2.0.1    @amzn2-core
java-1.8.0-openjdk-headless-debug.x86_64

./profiler.sh start -e alloc 32717
No AllocTracer symbols found. Are JDK debug symbols installed?

```

Thanks,
Roy

**Comment by apangin** [comment]
You need to install external debug symbols (aka *debuginfo*). This is not the same as *"debug"* package and not the *"devel"* package.

I obviously can't list all possible ways to install debuginfo, since there are hundreds of different Linux distributions with their own ways to manage software packages.

E.g. on CentOS, Fedora and other YUM-based distributions, this could be done with [debuginfo-install](http://man7.org/linux/man-pages/man1/debuginfo-install.1.html) utility:
```
debuginfo-install java-1.8.0-openjdk
```

If you still have problems installing debug symbols, consider using a JDK with embedded symbols, e.g. [Liberica JDK](https://bell-sw.com/pages/java-8u232/)

**Comment by RoySunnySean007** [comment]
Thanks @apangin for ur kindly help!  "debuginfo-install" utility, it DOES work!
I created a pull request https://github.com/jvm-profiling-tools/async-profiler/pull/265 for it, pls kindly approve this PR if there is no any concern.


Thanks,
Roy
