### ISSUE TITLE
Thread state in JFR file is always STATE_RUNNABLE even with wall profiler

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#279]
When using the `-e wall` option in combination with JFR, the thread state may be blocked or waiting. However, it's hard-coded to runnable.

https://github.com/jvm-profiling-tools/async-profiler/blob/2557363892b7f83dec4c652ca1b19e50e21877e4/src/flightRecorder.cpp#L696

**Comment by apangin** [comment]
Yes, this is a known problem. I haven't decided yet what thread state to put here.

1. First, because async-profiler works not only with Java threads, but also with native threads that do not have a Java thread state.
2. As I've shown in my [presentation about profiling](https://github.com/apangin/codeone2019-java-profiling), Java thread state is sometimes misleading. E.g. most of commonly used Java profilers show that a thread executing `Socket.read` is always in `RUNNABLE` state, even if the thread is actually idle waiting for incoming data. Or the other way round: a thread executing `Unsafe.park` is always considered in `WAITING` state, though parking/unparking often consumes much CPU time.

   Since async-profiler claims to be fair, I don't really want to rely on erroneous Java thread states.
3. A better option is probably to use OS-level thread states (Running / Sleeping / Waiting in uninterruptible disk sleep etc.) However, these states do not have an exact match in JFR format, and reusing Java thread state names will be probably confusing.

   Also, obtaining an OS thread state is subject to race conditions: e.g. a thread may change its state between the state is queried and the moment when the thread receives the profiling signal.

I'm open to input from the community. What are the use cases, and what kind of thread states do you expect to see in async-profiler results?

**Comment by franz1981** [comment]
@apangin +100 for the current behaviour TBH

As per https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.State.html#RUNNABLE:
```
Thread state for a runnable thread. A thread in the runnable state is executing in the Java virtual machine but it may be waiting for other resources from the operating system such as processor.
```
For https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.State.html#WAITING can be seen that:
```
Thread state for a waiting thread. A thread is in the waiting state due to calling one of the following methods:
- Object.wait with no timeout
- Thread.join with no timeout
- LockSupport.park
```
According to the current stated javadoc I don't think you could have made a better choice :)

**Comment by felixbarny** [comment]
I'm mainly interested in whether a stack trace is on or off CPU, so the exact Java thread state is not as interesting to me. If I had that information, I could basically do both CPU and wall profiling at the same time by either just looking at the on-CPU call stacks (=cpu profiling) or by looking at both on-CPU and off-CPU call stacks (=wall clock profiling).

**Comment by apangin** [comment]
I did some experiments to find if async-profiler can record thread state during wall clock sampling.

It turns out that the straightforward approach does not work well. On Linux, the only way to get the actual thread state in the system, seems to be reading from [`/proc/[pid]/task/[tid]/stat`](http://man7.org/linux/man-pages/man5/proc.5.html). This involves several syscalls, and the result is a long line with ~50 stats. No wonder, this is NOT a cheap operation.

Measurements showed that sampling of 8 threads with their states takes about 1 ms. Without thread states, this takes 0.1-0.2 ms. Quite a big overhead. Furthermore, by the time a signal is sent to the thread, the state may become obsolete.

So I decided to go a different way. The sampler sends signals to all threads, and the signal handler tries to discover thread state by analyzing CPU registers and the last executed instruction. If a thread was interrupted on an instruction other than `syscall`, the thread is considered RUNNABLE. Otherwise we do some magic of checking the syscall type, its return value etc.

The results look promising. After filtering out SLEEPING threads, the profile looks pretty much similar to what we get with CPU profiling. We can even distinguish blocked system calls from runnable on-cpu syscalls. No performance overhead, no race conditions.

I committed the fix. So far only two states are distinguished: `STATE_RUNNABLE`, and `STATE_SLEEPING`. The values reflect thread states in the operating system, not Java thread states.

**Comment by apangin** [comment]
Merged into master.

**Comment by niufei8888** [comment]
> So I decided to go a different way. The sampler sends signals to all threads, and the signal handler tries to discover thread state by analyzing CPU registers and the last executed instruction. If a thread was interrupted on an instruction other than `syscall`, the thread is considered RUNNABLE. Otherwise we do some magic of checking the syscall type, its return value etc.

@apangin Can you help elaborate more about this part?

More specifically, I'm trying to understand why, at [this point](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/wallClock.cpp#L50), a thread's current instruction being a `syscall` is considered as sleeping. 

Thank you in advance.

**Comment by apangin** [comment]
@niufei8888 Signal handler cannot interrupt a running thread in the middle of syscall execution (kernel is not preemtible by userland code). If a signal is sent while a thread is inside the kernel, the OS will defer the signal until return from a system call.

**Comment by niufei8888** [comment]
@apangin Thank you for the reply. I think your comments mean that if async-profilers happens to signal an on-kernel thread, then `WallClock::signalHandler` can be delivered only at the end of the syscall (as OS defers the userland codes). With that, however, I'm still not quite understand why we can say the thread being signaled is at the idle state.

**Comment by apangin** [comment]
@niufei8888 If a busy thread is signaled while being in kernel, it will finish current system call and will proceed with a signal handler afterwards. In this case, PC will point to the first instruction after `syscall`.

See [signal(7)](https://man7.org/linux/man-pages/man7/signal.7.html) for the details about signal delivery and interruption.

**Comment by niufei8888** [comment]
@apangin Thanks. I did more research, and I think I have an answer for the part that confused me. I was wondering why a thread in `syscall` is marked as sleeping. The kernel will indeed spend time running on-CPU when taking a `syscal`, but it's also fair to say "a `syscall` is mostly off-CPU blocking for the services". Hope that makes sense.
