### ISSUE TITLE
What does it mean by "skipped" when doing memory allocation profiling? 

### ISSUE THREAD

**Issue by wenleix** [jvm-profiling-tools/async-profiler#291]
Example: 

```
Total samples:         3308476
Non-Java:              18 (0.00%)
Skipped:               1990244 (60.16%)

Frame buffer usage:    37.1651%
```

The default memory allocation profiling complaints frame buffer so I increased the memory buffer size by -B

**Comment by apangin** [comment]
`Skipped` means the stacktrace hasn't been collected for this sample due to high contention (to avoid long pauses of application threads).

Normally, the amount of skipped samples should be very low. Such a high value may indicate something wrong with JVM options or profiler settings. What are the JVM and profiler options? have you tuned TLABSize or something?

See #261 for more information.
