### ISSUE TITLE
Question - profiling CPU and wall at the same time

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#311]
Hi, is it possible to run async-profiler to more then 1 event at the time and save it in collapsed format? 
If no, is it safe to run 2 async-profilers on the same JVM at the same time?

Best regards.

**Comment by apangin** [comment]
1. There is no need to run CPU and Wall profiler at the same time, since wall-clock profiler already collects information about CPU intensive methods. For every sample, wall-clock profiler detects whether the sampled stack trace was taken on-CPU or off-CPU. This data is stored in JFR format as a thread state: `STATE_RUNNABLE` for on-CPU samples, and `STATE_SLEEPING` for off-CPU ones. Basically, the set of `STATE_RUNNABLE` samples gives you the CPU profile. See #279 for details.

2. Right now I'm working on the feature to collect other events together, i.e. cpu+alloc+lock at the same time: #150

3. Yes, it's already possible to load 2 or more profiler instances to collect different events, but in this case the names of the agent libraries should differ. E.g. the first profiler is `libasyncProfiler.so`, and the second one is `libasyncProfiler2.so`.

**Comment by krzysztofslusarski** [comment]
Thank you for quick response.
