### ISSUE TITLE
Invalid output format should result in an error

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#326]
If you mistype output format, for example:
./profiler.sh stop <PID> -o collapse
there is no error, but the output is generated in default format.

Maybe a better way would be throwing an error?

**Comment by apangin** [comment]
Yes, printing an error in this case might be *slightly* better... or not. The issue is not that trivial.

1. Should an error be thrown by `profiler.sh` or by the agent?

    `profiler.sh` is a thin front end for controlling the agent. In order to keep it simple and avoid extra maintenance overhead, I wouldn't like to overload it with much logic. On the other hand, the agent's command line policy is to ignore unknown options for the sake of forward and backward compatibility - this already helped us in our production environment, where different services may use different versions of async-profiler at the same time.

2. Current behavior is not too bad. I mean, the output in a different format is already a sign that something is wrong with the profiler options. It's OK to correct the options and re-run the command: `stop` can be called multiple times in a row with different output options - it's actually a feature to dump the same profile in different formats.

3. When I run `stop`, my primary intention is probably to cease profiling immediately. Even with a wrong `-o` option, I will reach the goal. I can then correct command line, and dump the profile in the other format. But if the error is thrown, I will probably miss the opportunity to stop the profiler at the desired time.

For the above reasons, I suggest to leave the behavior as is.
