### ISSUE TITLE
Dumping a compressed collapsed format

### ISSUE THREAD

**Issue by egwepas** [jvm-profiling-tools/async-profiler#354]
I'm back with a question / suggestion : still in my quest of long duration profiling, do you think it would be a good addition to be able to dump a gzipped collapsed format ?

Before i've been using the dumpCollapsed method then writing it to disk via a GzipOutputstream. But it's getting too heavy on memory.

Right now i'm switching to JFR because this format seems more compact.

However i'm wondering if it would be possible for async-profiler to directly output a gzipped collapsed format (no intermediate storage in a huge String) ?

**Comment by apangin** [comment]
Using JFR format for long running profiling sessions is the right way to go, as it's more compact and at the same time more informative than other formats supported by async-profiler. In future, I plan to make JFR the primary output format.

I don't think there will be an option do dump gzipped format directly (to avoid extra dependencies and complexity), but I'll consider extending Java API to allow dumping to an arbitrary user-provided `OutputStream`.

BTW, if you end up writing output to disk, why calling `dumpCollapsed`, which pumps all data through the heap, instead of `execute("stop,file=output.collapsed")`, to dump collapsed format to disk and possibly compress it later?

**Comment by egwepas** [comment]
Hi,
That is indeed what I switched to.

I've been trying the jfr foramt, but i have a doubt regarding the resume command. Is it working properly ?
To me it seemed like the ouput file is starting from zero after resume, but maybe I missed something.

**Comment by apangin** [comment]
Right, JFR+resume needs to be fixed. I created a new issue #356 to address this.

**Comment by apangin** [comment]
Made stop/resume compatible with JFR output.
