### ISSUE TITLE
Presence of 'clone' stack in flamegraph

### ISSUE THREAD

**Issue by fvanaeken-sn** [jvm-profiling-tools/async-profiler#358]
This might not be an issue, and arguably off-topic, but I am puzzled by the presence of a 'clone' stack in a flamegraph of a Java application (see below).

Does the graph indicate that the 'clone' method is using a significant part of the total CPU cycles, but that the callers of the 'clone' method do not?

Also, why would 'clone' call 'start_thread'?

![flamegraph_clone](https://user-images.githubusercontent.com/70725149/95798614-57615380-0ca7-11eb-956f-488f292cb993.jpg)

**Comment by apangin** [comment]
This is not a Java method `Object.clone`, but rather a system [`clone`](https://man7.org/linux/man-pages/man2/clone.2.html) function. In Linux, `clone` syscall is used to create a new thread. Basically, every thread except the primordial one starts with `clone` - that's why you see it at the very bottom of the graph.

The red part on the right side of the graph presumably belongs to VM threads, particularly, GC and JIT compiler threads. And yes, GC and JIT compilation make take significant amount of CPU time. I suggest installing [JDK debug symbols](https://github.com/jvm-profiling-tools/async-profiler/#installing-debug-symbols) in order to see exact JVM function names instead of just `libjvm.so`.

**Comment by fvanaeken-sn** [comment]
Makes sense. Thank you, Andrei.
