### ISSUE TITLE
Using async-profiler from alpine with external jattach

### ISSUE THREAD

**Issue by anouarchattouna** [jvm-profiling-tools/async-profiler#362]
Hello,

Is there a way to use `async-profiler` to generate flame graphs on an `alpine` using an external `jattach` and not the one from `$SCRIPT_DIR/build/jattach`?
By external package I mean https://github.com/apangin/jattach#alpine-linux like recommended at https://github.com/jvm-profiling-tools/async-profiler/issues/207#issuecomment-472467180

I am running `async-profiler` on an `alpine` container and I am having same problem like https://github.com/jvm-profiling-tools/async-profiler/issues/207.

```bash
bash-5.0# java --version
openjdk 11.0.9 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
bash-5.0# /async-profiler/profiler.sh -d 10 -f /tmp/flamegraph.svg --all-user 1
/async-profiler/profiler.sh: line 68: /async-profiler/build/jattach: No such file or directory
bash-5.0# ls -la /async-profiler/build/jattach
-rwxr-xr-x    1 root     root         18880 Mar 17  2020 /async-profiler/build/jattach
```

Best,

**Comment by apangin** [comment]
I have no idea how an external jattach can be useful, since jattach bundled with async-profiler is *exactly the same* as the one from [jattach project](https://github.com/apangin/jattach).

To run async-profiler on Alpine Linux, make sure to use `async-profiler-*-linux-musl-x64` package, not `async-profiler-*-linux` (glibc).

**Comment by anouarchattouna** [comment]
Fair enough, thank you
