### ISSUE TITLE
Can't get Deoptimization events

### ISSUE THREAD

**Issue by sharonnorman** [jvm-profiling-tools/async-profiler#373]
I'm using Async Profiler 1.8.2  and trying to get deoptimization events following your advise in: 
https://stackoverflow.com/questions/64424775/how-can-i-catch-jits-deoptimization-events-like-unstable-if-with-jnijvmti

When using -e Deoptimization::uncommon_trap_inner I'm getting nothing.

Here is the list supported by my JVM:
[ped@asf-cccd ~]$ /async-profiler/profiler.sh list jps
Basic events:
  cpu
  alloc
  lock
  wall
  itimer
Java method calls:
  ClassName.methodName
Perf events:
  page-faults
  context-switches
  cycles
  instructions
  cache-references
  cache-misses
  branches
  branch-misses
  bus-cycles
  L1-dcache-load-misses
  LLC-load-misses
  dTLB-load-misses
  mem:breakpoint
  trace:tracepoint

Why am I getting nothing ?

**Comment by apangin** [comment]
Either no deoptimization events happen during profiling, or perf events are unavailble due to system configuration. In the latter case, there must be an error in the JVM logs.

Are the any warnings in the console of the target JVM when you start profiling?
What does `profiler.sh start -e Deoptimization::uncommon_trap_inner jps` print?

**Comment by apangin** [comment]
Closing the issue, since there has been no feedback after the last answer.

**Comment by sherman** [comment]
Probably has the same problem.
JDK 14. Try to get deopt events:
```
./profiler.sh -d 30 -e Deoptimization::uncommon_trap_inner -o jfr -f /root/deopt4.jfr 1
```
No warnings/error, but when I watching in the event browser can't see any deopt. event (but I'm sure there are because I can see it on flamegraph while profiling).

**Comment by sherman** [comment]
Can see the events in console output.

--- Execution profile ---
Total samples       : 322

Frame buffer usage  : 0.0175%

--- 160 events (49.69%), 160 samples

**Comment by apangin** [comment]
@sherman Tried the same command line as yours with JDK 14, and the result .jfr expectedly had stack traces ending with `Deoptimization::uncommon_trap_inner`.

Are you sure you're opening the right file? 982,433 Method Profiling Sample events look suspicious.

Can you show the contents of Flight Recorder | Recording Setting (from the Event Browser)?

**Comment by sherman** [comment]
@apangin 
![Screenshot from 2021-04-08 10-08-52](https://user-images.githubusercontent.com/65062/113983505-a6e99c00-9852-11eb-8b93-e0b81755978f.png)
![Screenshot from 2021-04-08 10-09-17](https://user-images.githubusercontent.com/65062/113983511-a81ac900-9852-11eb-884f-f3e1da28d07e.png)
![Screenshot from 2021-04-08 10-09-35](https://user-images.githubusercontent.com/65062/113983512-a81ac900-9852-11eb-9a49-d598d9c3493f.png)

**Comment by sherman** [comment]
I double-checked the file (generated a new one) and observing the same result.
![Uploading Screenshot from 2020-11-30 18-14-25.png…]()

**Comment by sherman** [comment]
![Screenshot from 2021-04-08 10-17-41](https://user-images.githubusercontent.com/65062/113984376-b1f0fc00-9853-11eb-9d01-443cf394a2fe.png)

**Comment by sherman** [comment]
As I can see, the stack-traces are correct (looks like deopt. points), but somehow it's not classified as deopt. events.

--- 855 events (56.03%), 855 samples
  [ 0] Deoptimization::uncommon_trap_inner(JavaThread*, int)
  [ 1] jdk.internal.math.FloatingDecimal.readJavaFormatString
  [ 2] jdk.internal.math.FloatingDecimal.parseDouble
  [ 3] java.lang.Double.parseDouble

**Comment by apangin** [comment]
> it's not classified as deopt. events in UI

They shouldn't. From async-profiler's perspective, `Deoptimization::uncommon_trap_inner` is just some arbitrary function name. It can profile any other function the same way, and the samples will be logged in JFR under `Method Profiling Sample` event type:

![uncommon_trap](https://user-images.githubusercontent.com/1749416/114011539-ff7a6280-986d-11eb-922a-e41b7fa82954.png)

**Comment by sherman** [comment]
Interesting. Looks like I misunderstood your initial post.

When I run the command (./profiler.sh -d 30 -e Deoptimization::uncommon_trap_inner -o jfr -f /root/deopt4.jfr 1), I expect to see deoptimization events (as I see it when I record a "flight" by the native jfr tool). And the most important part (for me) of the deopt. event is a reason field.

So, my question, is how I can get deoptimization events (with the reason field) using async-profile (or it's impossible at the moment)?

**Comment by apangin** [comment]
@sherman Async-profiler does not capture deoptimization reason, and I'm not sure it will. There is no intention to replicate all JFR features; I would rather make async-profiler work *together* with JFR.

However, what I *am* going to implement some day is capturing the specified function argument. Deoptimization reason will be a special case of that (as the reason is passed as an argument to `uncommon_trap_inner`).

At the moment, you can still get useful information from async-profiler: it records bytecode indices and line numbers. If you look at the top Java frame of the deoptimization stack, you'll find at which bytecode the deoptimization happens. This may give an idea about the deoptimization reason. The most common reasons are

- `unstable_if` for `if*` bytecodes;
- `class_check` for `invokevirtual`/`invokeinterface` and `checkcast`;
- `null_check` for field, array, and invoke bytecodes; and so on.
