### ISSUE TITLE
Can Async Profiler only profile specified packages?

### ISSUE THREAD

**Issue by jyanJing** [jvm-profiling-tools/async-profiler#381]
Hi Team,

My company uses AsyncProfiler in pretty much all the core services and we benefit from it a lot. However, my team writes library code and I found it is a little tricky to tell library performance when doing Async Profiling with services, since most of library code is shallowed by application logic, I have only see a few methods showed up in some profiles and it only happens when something went wrong.

However, it is very valuable for our own knowledge to know which part of library code is on a hot path and needs our attention to optimize. 

So I was wondering: 
1. if there is a way for AsyncProfiler to only profile a specific package? In our case, the library package. 
2. if AsyncProfiler can output how many times each method is called, instead of the CPU time of that method?

Thank you for looking into this!

**Comment by apangin** [comment]
1. Use `-I`/`-X` options to include or exclude stack traces with the given pattern.
E.g. if running with `-I org.mycompany.*` option, the output profile will include only stacktraces containing `org.mycompany` package.
The corresponding agent options are `include=org.mycompany.*` and `exclude=...`

2. It's possible to count invocations of a particular method or invocations of all methods of a given class.
E.g. `-e java.util.Properties.getProperty` will count all calls of `getProperty` method with the corresponding call stacks.
`-e org.mycompany.SomeClass.*` will count all invocations of methods in `SomeClass`. Profiling multiple classes in a similar way is not supported (yet).

Note: Java method profiling uses *instrumentation* rather than *sampling*. This may notably degrade performance if this method is called too often.

**Comment by jyanJing** [comment]
Thank you @apangin for the details! 
Following up on #1. If we filter stack trace by a pattern, would it be a pre filter or post filter? How much would it affect the performance of a service?

**Comment by apangin** [comment]
Filtering is performed when dumping results. They do not affect runtime performance.

CPU profiling overhead can be tuned with `-i` (interval) option. The default interval is 10 ms, which typically allows profiling applications in production without significant performance impact.

**Comment by apangin** [comment]
Since there is no further feedback, I assume the question is answered.
