### ISSUE TITLE
Any plans to support macOS at least for heap-profiling ?

### ISSUE THREAD

**Issue by normanmaurer** [jvm-profiling-tools/async-profiler#42]
Not sure if this is the right place for asking but I was wondering if you are considering adding support for heap profiling on macOS or will this stay linux only ?

**Comment by apangin** [comment]
I'll eagerly do this if someone donates me a MacBook for development ;)

Seriously, though, there should not be too much work. Even CPU profiling is feasible except for kernel stacks, if we take good old `setitimer` API instead of perf events. I'll try to do this later. Or I'll be glad to accept contributions.

**Comment by normanmaurer** [comment]
Let me see if I can work on a patch

**Comment by apangin** [comment]
Resolved in #56.
Heap profiling is now fully supported on macOS. CPU profiling is also supported, but limited only to Java code.
