### ISSUE TITLE
Profiling with cpu/wall events on Zing yeilds unusable results

### ISSUE THREAD

**Issue by vyazelenko** [jvm-profiling-tools/async-profiler#425]
Here is an example using the https://github.com/spring-projects/spring-petclinic project doing both CPU profiling (i.e. `./profiler.sh -d 30 -e cpu --total -f ...`) and wall-clock profiling (i.e. `./profiler.sh -d 30 -e wall --total -f ...`) on Zulu (**`OpenJDK 64-Bit Server VM (25.292-b10) for linux-amd64 JRE (Zulu 8.54.0.21-CA-linux64) (1.8.0_292-b10), built on Apr 6 2021 10:48:03 by "zulu_re" with gcc 4.4.7 20120313 (Red Hat 4.4.7-3)`**) and Zing (**`Zing 64-Bit Tiered VM (1.8.0_282-zing_21.03.0.0-b6-product) for linux-X86_64, built on Mar 30 2021 06:31:15 by buildmaster with gcc-7.4.0`**) JVMs (see [all profiles](https://github.com/jvm-profiling-tools/async-profiler/files/6400167/unknown.zip)):
- cpu
  * Zulu with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`
![zulu-cpu](https://user-images.githubusercontent.com/696855/116585787-077f6c80-a919-11eb-89ec-258f2c941b39.png)
  * Zing with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`
![zing-cpu](https://user-images.githubusercontent.com/696855/116585832-136b2e80-a919-11eb-8957-7d4fe331e4c3.png)
  * Zing with `-XX:+UnlockDiagnosticVMOptions -XX:+PreserveFramePointer`
![zing-fp-cpu](https://user-images.githubusercontent.com/696855/116585855-1a923c80-a919-11eb-9d6d-bbf4ae907aaf.png)
- wall
  * Zulu with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`
![zulu-wall](https://user-images.githubusercontent.com/696855/116585956-34338400-a919-11eb-9ab1-6725401934ed.png)
  * Zing with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`
![zing-wall](https://user-images.githubusercontent.com/696855/116585991-3dbcec00-a919-11eb-8707-9629a78cd207.png)
  * Zing with `-XX:+UnlockDiagnosticVMOptions -XX:+PreserveFramePointer`
![zing-fp-wall](https://user-images.githubusercontent.com/696855/116586018-46adbd80-a919-11eb-96e1-b0ba3ea5c232.png)

As can be seen from the above the `cpu` profiles on Zing have lots of samples shown as `[unknown]` and in the `wall` mode as `[not_walkable_java]`. In both cases the profiles are unusable for actual performance analysis.

**Comment by nitsanw** [comment]
From my understanding of the functionality involved on both Zing and Async-Profiler, this looks like an issue with the Zing implementation of `AsyncGetCallTrace`(this is probably my fault, I worked on it back in the day). This used to work at some point. It might be that the implementation was never extended to the Falcon compiler. To verify this line of thinking I would force Zing to use C2 (`-XX:+UseC2` if IIRC).

I would expect Zing engineers would be able to comment on the current state of Async-Profiler support. /cc @giltene.

**Comment by apangin** [comment]
I agree with Nitsan - this seems more like AsyncGetCallTrace implementation problem.
I'm afraid, it's behind async-profiler capabilities to deal with that.

**Comment by apangin** [comment]
I agree with Nitsan - this seems more like AsyncGetCallTrace implementation problem.
I'm afraid, it's behind async-profiler capabilities to deal with that; that needs to be addressed from JVM side. I'll ask colleagues from Azul what they think.

**Comment by leelamv** [comment]
When signal is received, AsyncGetCallTrace api collects two details for each frame of the stack trace . They are a) BCI (byte code index) b) corresponding method. Method is returned in the form of jmethodID . jmethodID  is JNI transferable structure. To collect the details, we need to walk the frames and find corresponding method and get its jmethodID and bci. 

Methods in some VM implementations comes from "relocatable address space" (aka Perm Gen) and some implementations comes from "non-relocatable address space" (aka MetaSpace).  

(Now, the key part) To "safely" read methods which come from Perm Gen. Thread needs to be qualified (i.e) Its current state should be in " in vm" (typically means running in libjvm code) or "in java"(running java code)  . Thread which is in "in native" (running in native libraries - c/c++) can't read methods safely.  However, vm implementations which have methods in MetaSpace, thread can safely read them. 

My guess is that app corresponding to this issue is doing lot of "jni transitions" and running in "native mode". 

Zing keeps the class info ( internally called Klass or KlassOop) and methods (internal called Methods or methodOops) in PermGen (which is relocating heap ). Current implementation of AsyncGetCallTrace in Zing checks for the "thread state" and if it is "in native"and return "not_walkable_java" . Basically, it wouldn't "transition" to "safe" state where it can safely walk the stack. Simple reason for that is, "transition" of thread state has other side effects which needs to honored. We decided to not do the transition in the signal handler. Note that for a sampling  based  profilers using timer signals like async_profiler, AsyncGetCallTrace is called from a signal handler. 

We are currently working on few solutions to make this better. We will notify when it is ready.

Thanks.

**Comment by vyazelenko** [comment]
@leelamv Just tested with Zing 11 and got the same results, i.e. the `wall` profile has mostly `[not_walkable_java]` frames and the `cpu` profile is dominated by the `[unknown]` frames. From your explanation above I would assume that Zing 11 would be much better, because it is using MetaSpace. Was I wrong to assume that?

**Comment by leelamv** [comment]
@vyazelenko 
Currently, any version of Zing supports only perm gen. So , i would expect the same behavior.

**Comment by apangin** [comment]
I'll close the issue, as I have no plans to fix this from async-profiler side.
