### ISSUE TITLE
Crash on Zing while doing `lock` profiling

### ISSUE THREAD

**Issue by vyazelenko** [jvm-profiling-tools/async-profiler#426]
I've observed a JVM crash while doing `lock` profiling on Zing JVM. Here is a redacted portion of the crash log:
```
#
# An unexpected error has been detected by Java Runtime Environment:
#
#  Internal Error (src/share/runtime/thread.cpp:604), pid=176401, tid=177505
#  guarantee(thread == this && JavaThread::current()->jvm_locked_by_self()) failed: _ref_buffer_array without jvm_lock
#
# Java VM: Zing 64-Bit Tiered VM (1.8.0_282-zing_21.02.1.0-b3-product-azlinuxM-X86_64, mixed mode)
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x62006c600000):  JavaThread "<redacted>" [JVM thread_state=_thread_in_native, locked by self running, polling bits: NONE , id=177505, stack(0x7f275a3f3000,0x7f275a5f3000), java prio=5, os prio=0, sched=SCHED_OTHER]

Stack: [0x7f275a3f3000,0x7f275a5f3000],  sp=0x7f275a5ef2b0,  free space=2032k
Native frames: (J Jn Jo=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x9fbc12]  VMError::report(staticBufferStream*)+0x972
V  [libjvm.so+0x9fcd9e]  VMError::report_and_die()+0x21e
V  [libjvm.so+0x9e1777]  report_vm_error(char const*, int, char const*, char const*)+0x57
V  [libjvm.so+0x9420c3]  Thread::set_old_gen_ref_buffer(HeapRefBuffer*)+0x1e3
V  [libjvm.so+0x33354d]  oopDesc* GPGC_LVB::lvb_oop_fixup<(OopHelper::EncodingHint)0>(oopDesc*, oopDesc* volatile*)+0x16d
V  [libjvm.so+0x80e356]  JvmtiEnvBase::get_stack_trace(JavaThread*, int, int, _jvmtiFrameInfo*, int*)+0x7a6
V  [libjvm.so+0x7ff7b4]  JvmtiEnv::GetStackTrace(JavaThread*, int, int, _jvmtiFrameInfo*, int*)+0xb4
C  [libasyncProfiler.so+0x2687f]  Profiler::recordSample(void*, unsigned long long, int, Event*)+0x26f
C  [libasyncProfiler.so+0x22073]  LockTracer::MonitorContendedEntered(_jvmtiEnv*, JNIEnv_*, _jobject*, _jobject*)+0x123
V  [libjvm.so+0x821fab]  JvmtiExport::post_monitor_contended_entered(JavaThread*, ObjLock*)+0x21b
V  [libjvm.so+0x8effec]  ObjLock::enter(JavaThread*)+0x41c
V  [libjvm.so+0x9373ac]  ObjectSynchronizer::lock(oopDesc*, MonitorInflateCallerId)+0x38c
V  [libjvm.so+0x91f876]  SharedRuntime::monitorenter(JavaThread*, oopDesc*)+0x96
v        ~StubRoutines::c2_lock
...
J  (C2)  com.lmax.disruptor.BatchEventProcessor.run()V
J  (C2)  java.lang.Thread.run()V
v        ~StubRoutines::call_stub

```

**Comment by apangin** [comment]
I profiled locks many times, but haven't seen such an error.
How often does it happen? Do you have a reliable reproducer?
I have a guess why this could happen, but it would be nice to have a test to verify the idea.

**Comment by vyazelenko** [comment]
@apangin It happened twice while collecting several dozens of profiles for different event types. I assume that it happened while collecting the `lock` profile, because the stacktrace contains `[libasyncProfiler.so+0x22073]  LockTracer::MonitorContendedEntered`.

Unfortunately I no longer have access to the system where the crash was observed and so far I was not able to reproduce it locally.

**Comment by apangin** [comment]
Zing support is not among current async-profiler priorities, sorry. I may reconsider this, if there are customers willing to sponsor Zing-related work. Since the problem cannot be reproduced easily, I don't think it worth spending more time on it.

**Comment by leelamv** [comment]
Hi @apangin and @vyazelenko,

This issue is in a way a manifestation of "incorrect" use of internal apis of hotspot. Let me explain. 

Hotspot provided few public apis to collect stack trace. Few examples 
a) [AsyncGetCallTrace](http://psy-lob-saw.blogspot.com/2016/06/the-pros-and-cons-of-agct.html)
b) [JVMTI](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#GetStackTrace)

What these apis expected to do are thread contract checks. for ex:
a) Is Thread qualified to collect stack trace ?
b) Is Thread in expected thread "state" and transition to correct "state" to collect stack trace and more.. 

Missing the contract checks can have various manifestations and can possibly run into issues in future if not now. 

So why am i explaining all these for this issue ?

AsyncProfiler seems to  [find](https://github.com/jvm-profiling-tools/async-profiler/blob/91eab916343fe646f6ad266694312c9175f28e0f/src/vmStructs.cpp#L167) an "internal" jvm function and [calling](https://github.com/jvm-profiling-tools/async-profiler/blob/339aee5cfc911ba27c335bdb72108c862cb0216f/src/profiler.cpp#L584) it.

This direct calling of internal function lead the thread to enter hotspot code without "proper" thread state transition. If you are aware of hotspot code, there is macro called "JNI_ENTRY" which does all these for thread. 

Issue manifested saying, "Thread isn't qualified to access oops (java objects) directly at this point".  Proper thread state transition would make thread to qualify for entering hotspot code. 

Now why is it  happening with Zing.  Zing puts all its Classes and methods info in Perm Gen (Relocatable heap) and have explained about this [here](https://github.com/jvm-profiling-tools/async-profiler/issues/425#issuecomment-830058372) in detail. 

What are our possible next steps ?
 a) We should avoid calling this "internal function".  This is potential maintenance issue for the async profiler. See we have to find two different symbols by the cpp compiler "demangled" names.  Note that proper public facing apis aren't demangled and available for dlsym search. 

b) For the above, we need to understand the reason for using "internal" function instead  of calling the public api. Reading the history of changes, it seems like, we used this to handle incorrect thread state. If thread is in correct state, this could be a hotspot bug too. Understanding the issue and fixing it at right place will avoid doing this. I can volunteer to help if you provide details of the original issue. 

Thanks, 
Leela

**Comment by apangin** [comment]
That was my guess as well. Thank you for the detailed explanation how it works in Zing.
My long-term plan is to get rid of internal calls altogether, including [AsyncGetCallTrace](https://github.com/jvm-profiling-tools/async-profiler/issues/66).
