### ISSUE TITLE
additional view

### ISSUE THREAD

**Issue by araud** [jvm-profiling-tools/async-profiler#43]
Hello!

Nice work!

In addition to cmdline and flamegraph you might consider using this as view generator: https://github.com/01org/IntelSEAPI/wiki

It supports JIT symbols, stacks and many more things.

Please contact me if interested.

**Comment by apangin** [comment]
Looks interesting. Any suggestions on how to make this work with async-profiler?
As far as I understand from the project wiki, the tool relies on ITT_* instrumentation in the code, but this does not seem suitable, since async-profiler already collects samples with stack traces while running unmodified application.

**Comment by araud** [comment]
It takes writing an importer from your data into IntelSEAPI internal representation. Examples are here: https://github.com/01org/IntelSEAPI/tree/master/runtool/importers
Please contact me using one of the ways shown in my profile? I will help you to write it.

**Comment by apangin** [comment]
async-profiler already supports a number of output formats, including

- collapsed stack traces format which is as simple as CSV;
- call tree / backtrace views;
- Java Flight Recorder (.jfr).

JFR format is rich and extensible and supports nearly all features Java profilers can give. It has been recently open sourced along with its primary consumer - Java Mission Control. I assume that further development around presentation of profiler data should be based on this format.
