### ISSUE TITLE
Document interaction of profiler with DebugNonSafepoints

### ISSUE THREAD

**Issue by retronym** [jvm-profiling-tools/async-profiler#47]
The README calls out the use of `AsyncGetStackTrace` to avoid the safepoint bias problem.

It isn't clear to me if I have to remember to add `-XX:+DebugNonSafepoints` to the JVM options to profit from this. (My assumption is that I do.)

https://github.com/jvm-profiling-tools/honest-profiler/blob/master/src/main/cpp/agent.cpp#L35 mentions this JVM option in a comment about why an empty method is needed.

**Comment by nitsanw** [comment]
For HP there is no need to add the option as the presence of the agent on JVM load will auto enable it.

**Comment by retronym** [comment]
Thanks for the clarification.

**Comment by lic9** [comment]
@nitsanw is '-XX:+DebugNonSafepoints' required? Async Profiler has alread enabled JvmtiExport::should_post_compiled_method_load(), which should be good enough to make the jvm to record non-safepoints:

./src/share/vm/code/debugInfoRec.cpp-82-static inline bool compute_recording_non_safepoints() {
./src/share/vm/code/debugInfoRec.cpp-83-  if (JvmtiExport::should_post_compiled_method_load()
./src/share/vm/code/debugInfoRec.cpp:84:      && FLAG_IS_DEFAULT(DebugNonSafepoints)) {
./src/share/vm/code/debugInfoRec.cpp-85-    // The default value of this flag is taken to be true,
./src/share/vm/code/debugInfoRec.cpp-86-    // if JVMTI is looking at nmethod codes.
./src/share/vm/code/debugInfoRec.cpp-87-    // We anticipate that JVMTI may wish to participate in profiling.
./src/share/vm/code/debugInfoRec.cpp-88-    return true;
./src/share/vm/code/debugInfoRec.cpp-89-  }
./src/share/vm/code/debugInfoRec.cpp-90-
./src/share/vm/code/debugInfoRec.cpp-91-  // If the flag is set manually, use it, whether true or false.
./src/share/vm/code/debugInfoRec.cpp-92-  // Otherwise, if JVMTI is not in the picture, use the default setting.
./src/share/vm/code/debugInfoRec.cpp-93-  // (This is true in debug, just for the exercise, false in product mode.)
./src/share/vm/code/debugInfoRec.cpp:94:  return DebugNonSafepoints;
./src/share/vm/code/debugInfoRec.cpp-95-}

I think this is how Honest Profile works as well.

**Comment by apangin** [comment]
@lic9 The option is not needed if the agent is loaded at JVM startup (by using `-agentpath` option), but it is desired (though not required) if the agent is attached at run time. `CompiledMethodLoad` JVMTI event enables debug info, but only for methods compiled after the event is turned on.

**Comment by apangin** [comment]
@lic9 You're right: without `DebugNonSafepoints` there is a high chance that simple inlined methods will not appear in the profile.

**Comment by lic9** [comment]
@apangin would that also bias the results? Skimming the code, it seems like async profiler will drop samples whose _asyncGetCallTrace() returns negative num_frames and could not pop off top frame. This could happen to all Java stacktraces that have no decipherable compiled frame (no associated PcDesc at the specific pc or nearby pc due to missing _recording_non_safepoints option). In other words, only pc at safepoint or before safepoint could be recorded. Is that correct? If so it is better to show them as unknown or unwalkable instead of dropping them? Thanks!

**Comment by apangin** [comment]
@lic9 The absense of `DebugNonSafepoints` should not cause omission of samples. At least the enclosing Java frame can be recovered.
Even when something goes wrong, the samples with incomplete stack traces are counted and reported in summary.

**Comment by lic9** [comment]
@apangin I see. Those failed cases are recorded as 'Unknown (native/Java)' in plain text result but not shown on flamegraph. Thanks for the explanation!

**Comment by apangin** [comment]
@lic9 Sounds reasonable. Can you please open a separate issue for this?

**Comment by lic9** [comment]
@apangin Sure I will open a new issue and create a patch. Thanks!

**Comment by calvin1978** [comment]
@apangin ,  the README  hadn't  updated for   `-XX:+DebugNonSafepoints` yet :)

**Comment by apangin** [comment]
@calvin1978 Would you like to update it?

**Comment by Valloric** [comment]
This just bit me today. Please update the README to mention that `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` is necessary if attaching to a running process.

**Comment by jodzga** [comment]
How about this?
https://github.com/jvm-profiling-tools/async-profiler/pull/152

**Comment by apangin** [comment]
@jodzga Thank you! I've merged the proposed addition.
