### ISSUE TITLE
Incorrect behavior when JVM exits before profiling duration elapsed

### ISSUE THREAD

**Issue by atomashpolskiy** [jvm-profiling-tools/async-profiler#49]
Hi! Thank you for an awesome tool, it is a pleasure to use and has been very helpful to discover some subtle bugs in my code :)

I noticed a few minor issues when using time-capped `collect` command. All of them happen, when JVM exits before the configured duration of profiling session elapses:
- profiler does not exit immediately after JVM, but remains alive until the time elapses
- upon exiting the profiler prints `Could not start attach mechanism: No such file or directory` (I've commented redirection of output to /dev/null for debug purposes)
- if an output file was specified, then it contains only one line: `CPU profiling started`

Cheers,
Andrei

**Comment by apangin** [comment]
Thank you for the feedback. The problem is understood, however, it is not trivial to fix with the current attach mechanism. The profiling is done inside JVM process, and `profiler.sh` script just issues start and stop commands.

I have an idea how to deal with process termination, but I need to think it over.
