### ISSUE TITLE
Total samples in trivial case

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#504]
```
    public static void main(String[] args) {
        try {
            final AsyncProfiler asyncProfiler =
                    AsyncProfiler.getInstance("libasyncProfiler.dylib");
            final String standardParams = "event=" + Events.CPU + ",interval=1000000";

            String command = "start," + standardParams;

            asyncProfiler.execute("check," + standardParams);

            asyncProfiler.execute(command);
            System.out.println(asyncProfiler.execute("traces=10"));
            asyncProfiler.stop();
        } catch (IOException ioException) {
            throw new RuntimeException(ioException);
        }
    }

```

The simple example works in a weird way:

--- Execution profile ---
Total samples       : 2

But no more real samples:

Or

--- Execution profile ---
Total samples       : 3

--- 1000000 ns (100.00%), 1 sample
  [ 0] CallTraceStorage::collectSamples(std::__1::map<unsigned long long, CallTraceSample, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, CallTraceSample> > >&)
  [ 1] Profiler::dumpText(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, Arguments&)
  [ 2] Profiler::dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, Arguments&)
  [ 3] Profiler::runInternal(Arguments&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&)
  [ 4] Java_one_profiler_AsyncProfiler_execute0
  [ 5] one.profiler.AsyncProfiler.execute0
  [ 6] one.profiler.AsyncProfiler.execute
  [ 7] Main.main

**Comment by apangin** [comment]
This is kind of expected.

Since version 2.5, async-profiler got the feature to dump the interim results without stopping the profiling sesson. To avoid interruption, dumping is performed concurrently with the collection of samples. This means, the total number of collected samples may change right in the middle of printing.

If you print the results after profiling is stopped, e.g.
```
System.out.println(asyncProfiler.execute("stop,traces=10"));
```
the total number of samples will be consistent.

Alternatively you can dump results in another format, which is always consistent (e.g. `flamegraph`).

**Comment by toktarev** [comment]
ok, I considered it as a bug.
