### ISSUE TITLE
Stable names for binaries

### ISSUE THREAD

**Issue by pquentin** [jvm-profiling-tools/async-profiler#517]
Hi,

We're using automation to fetch the binaries from the GitHub releases, and are wondering: can you please stick with one convention for Linux aarch64 binaries? Here's what I'm seeing:

 * async-profiler-2.0-linux-aarch64.tar.gz
 * async-profiler-2.0-linux-arm.tar.gz 
 * async-profiler-2.5-linux-arm64.tar.gz
 * async-profiler-2.5.1-linux-arm64.tar.gz

Is `linux-arm64` the new name? (Any reason why you're not using `aarch64`?)

Thanks for this wonderful tool!

**Comment by pquentin** [comment]
(Sorry, I fat-fingered the "Submit new issue" button. I updated my post above.)

**Comment by apangin** [comment]
Sorry for the confusion.
What was earlier called `arm` and `aarch64` are now `arm32` and `arm64` correspondingly.

async-profiler has been ported to macOS/ARM64 since version 2.5, and this was accompanied by certain changes in package naming. The architecture of the Apple Silicon is typically [referred to](https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon) as `arm64` in Apple docs. Debian port to 64-bit ARM is also [called](https://wiki.debian.org/Arm64Port) `arm64`. So this name seems more consistent to me. I'll try to keep it in the nearest future, though I don't guarantee this will remain forever. The naming may change, for example, if async-profiler builds get more flavors.

**Comment by pquentin** [comment]
Thanks!
