### ISSUE TITLE
Using async-profiler in Kubernetes

### ISSUE THREAD

**Issue by TomGranot** [jvm-profiling-tools/async-profiler#552]
Hey @apangin!

Just wanted to drop by and mention that we recently added `async-profiler` to our [KoolKits](https://github.com/lightrun-platform/koolkits) project:

https://github.com/lightrun-platform/koolkits/blob/main/jvm/Dockerfile#L80-L84

KoolKits are an easy way to attach to a running pod, get access to the running process, and run various tools you would normally expect a local development machine to have (profilers, debuggers, etc...). No port forwarding or other configuration is necessary!

A couple of questions:
1. Would that be the canonical way to add `async-profilder` to a Dockerfile, or do you have a preferred installation method?
2. Would it be OK if I open a PR to the README of this repo that mentions KoolKits? I think it's a great way to help Kubernetes users get access to your profiler.

Looking forward to hearing from you!

**Comment by apangin** [comment]
Hi Tom,
1. The installation method is fine. I'm going to publish rpm/deb packages in future async-profiler versions, but so far unpacking .tar.gz should be OK. The only notice - you probably wanted `x64` build instead of `arm64`.
2. I don't think the documentation is an appropriate place to advertise any side product, especially if I don't use it myself on a daily basis. After all, there are already many projects that use or ship async-profiler.
However, you can write a post on [Discussions](https://github.com/jvm-profiling-tools/async-profiler/discussions) page, so that other people may find the information if they have a related question.
