### ISSUE TITLE
25% cpu time for log4j

### ISSUE THREAD

**Issue by asurovenko-zeta** [jvm-profiling-tools/async-profiler#577]
Hello,

I have collected my cpu events through async-profile
<img width="1176" alt="Screenshot " src="https://user-images.githubusercontent.com/80847074/161444876-d50ec81d-1e38-449a-9b7b-2461c04283a5.png">
And here's such picture. 25% for logging? For real? Why? What's the catch here?

My **log4j.xml** config file:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration name="Production log config">

    <Properties>
        <Property name="PATTERN_LAYOUT">%d{HH:mm:ss.SSS} %-5level [%t] %logger{36} - %msg%n</Property>
        <Property name="BASE_PATH">${env.SERVER_HOME:-.}/logs</Property>
    </Properties>

    <Appenders>
        <Console name="CONSOLE" target="SYSTEM_OUT">
            <PatternLayout pattern="${PATTERN_LAYOUT}"/>
        </Console>

        <RollingFile name="FILE"
                     fileName="${BASE_PATH}/log.log"
                     filePattern="${BASE_PATH}/server-%d{yyyy-MM-dd}.log.gz"
                     immediateFlush="false">
            <PatternLayout pattern="${PATTERN_LAYOUT}"/>
            <Policies>
                <TimeBasedTriggeringPolicy interval="1" modulate="true"/>
            </Policies>
            <DefaultRolloverStrategy>
                <Delete basePath="${BASE_PATH}" maxDepth="1">
                    <IfFileName glob="server-*.log.gz"/>
                    <IfAccumulatedFileCount exceeds="3"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingFile>

        <Async name="ASYNC_APPENDER" error-ref="CONSOLE">
            <AppenderRef ref="FILE"/>
            <JCToolsBlockingQueue/>
        </Async>
    </Appenders>

    <Loggers>
        <Root level="WARN">
            <AppenderRef ref="ASYNC_APPENDER"/>
        </Root>
    </Loggers>

</Configuration>
```

Thanks for help!

**Comment by apangin** [comment]
> 25% for logging? For real?

Yes, this looks plausible. I would believe async-profiler here :)

> Why? What's the catch here?

You are using `JCToolsBlockingQueue` plugin which employs a sort of busy waiting strategy for taking events from the log queue:

https://github.com/apache/logging-log4j2/blob/f72100df0decc9bda96b4d769822c4e48b2848fc/log4j-core/src/main/java/org/apache/logging/log4j/core/async/JCToolsBlockingQueueFactory.java#L134-L140

**Comment by franz1981** [comment]
@asurovenko-zeta 
I think the right place to report this is Log4j (ping @carterkozak ;)), but 

> 25% for logging? For real?

This is not what the profiling data is saying, really: it's a part of the story
https://github.com/apache/logging-log4j2/blob/f72100df0decc9bda96b4d769822c4e48b2848fc/log4j-core/src/main/java/org/apache/logging/log4j/core/async/JCToolsBlockingQueueFactory.java#L139
and
https://github.com/apache/logging-log4j2/blob/f72100df0decc9bda96b4d769822c4e48b2848fc/log4j-core/src/main/java/org/apache/logging/log4j/core/async/JCToolsBlockingQueueFactory.java#L51

shows that the parking strategy is taking some time, probably compating with the wakeup part to async write the logs: probably for your use case an hybrid wait strategy (or just yield) will work better.
let's continue on log4j issues ;)

**Comment by apangin** [comment]
@franz1981 The "parking" strategy in `JCToolsBlockingQueueFactory` does not really park:
https://github.com/apache/logging-log4j2/blob/f72100df0decc9bda96b4d769822c4e48b2848fc/log4j-core/src/main/java/org/apache/logging/log4j/core/async/JCToolsBlockingQueueFactory.java#L152

It's still busy waiting that repeatedly wastes CPU cycles on parking and immediate unparking.

**Comment by carterkozak** [comment]
For what it's worth, I'd recommend using log4j [fully asynchronous logging](https://logging.apache.org/log4j/2.x/manual/async.html#AllAsync) over the AsyncAppender. To be clear, the jctools queues are fantastic, but the log4j2 uses a different concurrency design for fully asynchronous logging which allows us to avoid many kinds of overhead.
Concretely, any time a mutable logevent is passed to an `AsyncAppender`, it is copied because the AsyncAppender will interact with the event in parallel to synchronous appenders on the application thread, however when all logging is async, ownership of the event can be passed along via references.
The ringbuffer also acts as a cache of reusable objects, thus avoids some allocation on potentially hot paths.
Finally, the 'work' (routing to appenders, formatting strings, etc..) all occurs on a background thread which only handles logging, reducing the performance volatility due to the logging framework on the application thread, and reducing logging-related latency.
I hope that's helpful, happy to chat through specifics if you like :-)

**Comment by franz1981** [comment]
Thanks @apangin, yep, I was assuming that was parking the thread for real :O

Thanks @carterkozak for the details ;)
