### ISSUE TITLE
memory size of async-profiler

### ISSUE THREAD

**Issue by juilewgg** [jvm-profiling-tools/async-profiler#596]
What's the memory size of the tool? (if its potential large size affects the application if executed on the same CPU)

**Comment by apangin** [comment]
Perhaps, by "size of the tool" you mean the increase of RAM footprint caused by profiler running?

Async-profiler works in the context of the target JVM process. It does not consume memory on its own, but the fact of using profiler may add to the RSS of the Java process being profiled.

The amount of extra memory depends on many factors which are mostly application-specific. E.g.
 - number of threads;
 - number of classes and methods;
 - depth of stack traces;
 - CPU utilization;
 - profiler settings;
 - length of the profiling session.

I can't know the memory overhead in your particular use case - it can be anywhere from a few megabytes to more than a gigabyte. A typical overhead is usually less than 100MB, but it may vary. In general, the shorter is profiling duration and the larger is profiling interval - the smaller is the overall memory overhead. For a regular profiling session of 30-60 seconds with the default sampling interval of 10ms you'll hardly notice any significant increase in memory usage at all.

**Comment by juilewgg** [comment]
Thanks for the reply. Seems that the extra RSS memory overhead is low. For the "size of the tool", I mean the how large of the software. From my point of view, the total size of async-profiler is around 2.4MB?

**Comment by apangin** [comment]
Ah, you mean on-disk usage. OK, the unpacked async-profiler directory is as small as 500KB.
