### ISSUE TITLE
Can I use async profiler to measure context switch cpu consumption?

### ISSUE THREAD

**Issue by qsLI** [jvm-profiling-tools/async-profiler#639]
We have a very large tomcat app，business are very complicated. 
We found that there are many threads and context switch very often. 
We want to figure out the influence on cpu usage of context switch.
Can we use async profiler?

**Comment by apangin** [comment]
You can certainly see context switch activity with async-profiler. But "context switch cpu consumption" sounds too ambiguous, it's not just one thing.

First, you can profile `-e context-switches` to find what code is the main source of these switches:

![context-switches](https://user-images.githubusercontent.com/1749416/186984421-e4d93fd8-16bb-4a9c-9cb5-2b054d41c173.png)

Note that all stack traces end with `schedule` kernel function. You can then run a generic CPU profiling too see the portion of CPU cycles spent in kernel scheduler.
For more accurate results, use `-e cycles` instead of `-e cpu`:

![schedule](https://user-images.githubusercontent.com/1749416/186983526-75e1a42c-2ad5-47de-b0e3-64dcc0489177.png)
Search for `schedule` on the flame graph. That will be the direct overhead of task switching.

However, the negative impact of context switching is not only related to scheduler. Invisible side effects can be even worse. When many tasks share the same core, they constantly evict each other's data from L1/L2 caches, resulting in slower execution of memory access instructions. Although async-profiler can also profile `cache-misses`, it's hard to correlate them with the intensity of context switches.
