### ISSUE TITLE
Was it intentional to mark release v1.8.8 as Latest?

### ISSUE THREAD

**Issue by poluektovaol** [jvm-profiling-tools/async-profiler#653]
**Steps to reproduce** 
- Hit https://github.com/jvm-profiling-tools/async-profiler/releases/latest

**Actual result:** v1.8.8 is Latest
**Expected result:** v2.8.3 is Latest

I was just wondering if marking v1.8.8 as Latest is intentional and we need to pin the version we use? (we used to just download latest before and were expecting getting v2+)

**Comment by apangin** [comment]
The [latest release](https://docs.github.com/en/rest/releases/releases#get-the-latest-release) in GitHub terminology is any published release made from a commit with the most recent date. It turned out that the most recent fix was in 1.x branch. One doesn't mark the latest release manually.

I plan to release a new version of 2.x soon, so the latest will automatically move to that one.
