### ISSUE TITLE
Is `--exclude` supported by jfr formats?

### ISSUE THREAD

**Issue by github-louis-fruleux** [jvm-profiling-tools/async-profiler#697]
Thanks for maintaining async-profiler. I really appreciate it.

I was playing a bit with the Java API, and I think for the JFR output format, the exclude filtering is not supported.

From what I am seeing, the exclude filtering is only called in the following three functions:
 - [dumpCollapsed](https://github.com/jvm-profiling-tools/async-profiler/blob/7eaefdb18f331962dc4c78c82322aec257e95c6c/src/profiler.cpp#L1246)
 - [dumpFlameGraph](https://github.com/jvm-profiling-tools/async-profiler/blob/7eaefdb18f331962dc4c78c82322aec257e95c6c/src/profiler.cpp#L1283)
 - [dumpText](https://github.com/jvm-profiling-tools/async-profiler/blob/7eaefdb18f331962dc4c78c82322aec257e95c6c/src/profiler.cpp#L1337)

I am not sure about how the [dump](https://github.com/jvm-profiling-tools/async-profiler/blob/7eaefdb18f331962dc4c78c82322aec257e95c6c/src/profiler.cpp#L1153) method is called from the Java API (if it is), but I don't see where the jfr events got excluded.

My questions are:
 - Is the `exclude` option supported for `jfr` output format?
 - How hard would it be to implement it? (I could give it a try if that's not too hard, but I have not done C++ in ages)

**Comment by github-louis-fruleux** [comment]
Found the [explanation](https://github.com/jvm-profiling-tools/async-profiler/issues/187#issuecomment-599220642)

I would like to make a PR to prevent someone else from falling in the same trap I did. Where would be the most appropriate place to document this option?

**Comment by apangin** [comment]
This seems to me an [XY problem](https://en.wikipedia.org/wiki/XY_problem).

Why would anyone want an `exclude` option for `jfr` in the first place? `jfr` is a binary format, which is hardly useful for a human without a proper viewer/parser tool. So, it's a job of a viewer tool to extract the information a user wants. It's actually cheaper just to write an event than to filter it, and filtering can be performed any time later while reading the output `jfr`.

`jfr2flame` converter included in async-profiler package already supports `--include`/`--exclude` options. If you have `.jfr` file, you can extract only those stack traces that match the given regular expression.

**Comment by github-louis-fruleux** [comment]
You are right, probably the converters are the best place to include/exclude due to the price to do it at runtime.

I don't see this option in the `jfr2pprof` converter. Would it be acceptable to you if I implement the same `--include` / `--exclude` options for this converter?

Also, how could I contribute to warn the end user that these options don't / won't be supported with jfr format?


For context, we are working on setup a phlare with an async + converter jfr2pprof exposed to an endpoint, à la `jpprof`. And in the profiles, we see a non-negligible part of the CPU spent handling the route.
This looks like a false positive to me to expose the route handle to end users, because it probably takes a few CPU%, but only for a small % of the time.
I don't know enough in this world of continuous profiling yet, but I feel like excluding the frame would be a solution.

Thanks for the support, I appreciate

**Comment by apangin** [comment]
To be honest, this still doesn't sound to me as a strong justification. That's how I see it from your explanation:

1. There is some third party viewer that supports `pprof` format but not `jfr`, so you want to convert `jfr` to `pprof`, despite that `jfr` is more flexible, has more features specifically for Java profiling, and is de facto standard in Java world, since it is natively supported by JDK, JMC, IDEA, etc.
2. That other viewer does not have filters, so you propose to move this task to the converter's responsibility.
3. The idea of filtering comes from an assumption that async-profiler shows something irrelevant (i.e. "false positive"). However, I fail to understand why this is "false positive", because if async-profiler shows something in CPU profile, it really means this code consumes CPU time in that proportion. The whole purpose of async-profiler is to show everything that spends CPU resources: whether it is in user code, libraries, JVM or even OS kernel.

Even though filtering would be an easy thing to add, I have a feeling that you're either trying to solve a problem in a wrong direction, or probably solve the wrong problem in the first place. Excuse me if I misunderstand the intention.

**Comment by github-louis-fruleux** [comment]
Thanks for the complete answer. I think you completely understood the question.

What I meant by "false positive" is the time spent profiling by the profiler itself in the context of continuous profiling. e.g. it shows up as X% of CPU consumed globally, which is true only for the time profile, which might represent only a small fraction of the time. So in fact the CPU spent globally in the profiler is X% * a really small fraction of the time.

But you are right, keeping the converter as simple as possible and moving that responsibility to the data plotter is probably the right way to do it.
Thanks for your answers

**Comment by github-louis-fruleux** [comment]
Also, sorry for insisting on that. But I think it could be worth documenting which options are compatible with which format.

I, unfortunately, spent a couple of hours understanding that the jfr format does not support filtering as other outputs do (which is completely justified). Where could I help document the `include` / `exclude` option?


We can probably close this thread, thanks again for the answers

**Comment by apangin** [comment]
If you wish, you may add a note in README where `-I include`, `-X exclude` options are [described](https://github.com/jvm-profiling-tools/async-profiler/blob/master/README.md?plain=1#L412).

**Comment by github-louis-fruleux** [comment]
Thanks for the support :)
