### ISSUE TITLE
Can't profiling java in a container from another container due to "Perf events unavailable."

### ISSUE THREAD

**Issue by yuzhichang** [jvm-profiling-tools/async-profiler#705]
I'm able to profile java in a container from host:

```
-- on host: (Java pid 207307 is inside container d26427a4dff8)
$ sudo docker cp build/libasyncProfiler.so d26427a4dff8:/
$ sudo bash ./profiler.sh -d 30 -o jfr -f /tmp/kfk.jfr --lib /libasyncProfiler.so -e cpu,alloc,lock --fdtransfer 207307
Profiling for 30 seconds
Done
```

However I'm not able to profile it from another container:
```
-- on host
$ sudo docker run -d --rm --name ubuntu_proc_priv3 --privileged --security-opt seccomp=unconfined --cap-add SYS_ADMIN -v /proc:/proc ubuntu /bin/bash -c 'while true; do sleep 60; done'
$ sudo docker cp async-profiler-2.9-linux-x64 ubuntu_proc_priv3:/
$ sudo docker exec -it ubuntu_proc_priv3 bash

-- on privileged container:
root@4b242de79e29:/# cd async-profiler-2.9-linux-x64/
root@4b242de79e29:/async-profiler-2.9-linux-x64# ./profiler.sh -d 30 -o jfr -f /tmp/kfk.jfr --lib /libasyncProfiler.so -e cpu --fdtransfer 207307
Unexpected connection from PID 0, expected from 1
[WARN] FdTransferClient send(): Broken pipe
[WARN] perf_event_open for TID 1 failed: Broken pipe
[WARN] FdTransferClient send(): Broken pipe
[WARN] perf_event_open for TID 146 failed: Broken pipe
...
WARN] perf_event_open for TID 238 failed: Broken pipe
[ERROR] Perf events unavailable
```

**Comment by Jongy** [comment]
This is the problem:

> `Unexpected connection from PID 0, expected from 1`

fdtransfer attempts to validate the PID of the alleged peer with the PID from the `SO_PEERCRED` request. Your 2 containers do not share a PID namespace, so they cannot see one another, hence the `SO_PEERCRED` returns PID 0.
fdtransfer uses it as a security measure (to prevent arbitrary processes from utilizing fdtransfer to get privileged perf access). Further, fdtransfer needs to reside in the PID namespace of the target process, because the JVM will request perf fds for specific TIDs, and they will be invisible for fdtransfer as it's not the same PID namespace.

fdtransfer itself was meant to run in host PID namespace. The workaround (if you're fine with it) is to add `--pid=host` to the `docker run` line of the privileged container.

**Comment by yuzhichang** [comment]
@Jongy Your suggestion works! Thanks!
