### ISSUE TITLE
Profiler doesn't work when MaxJavaStackTraceDepth set to -1

### ISSUE THREAD

**Issue by artspb** [jvm-profiling-tools/async-profiler#89]
When I run my application with `-XX:MaxJavaStackTraceDepth=-1` the profiler doesn't print any stack trace. The output consists of the following.

```
--- Execution profile ---
>Total samples:         38441
>Non-Java:              3681 (9.58%)
>GC active:             490 (1.27%)
>Unknown (native):      21475 (55.86%)
>Not walkable (native): 9409 (24.48%)
>Unknown (Java):        838 (2.18%)
>Not walkable (Java):   2533 (6.59%)
>Deopt:                 15 (0.04%)
>
>Frame buffer usage:    0%
```

Removing the option solves the problem. If it's expected behavior, it'd be great to document it in README.

**Comment by apangin** [comment]
Thank you for an interesting bug report! This is not an expected behavior, even for me :)

It turns out that AsyncGetCallTrace API for stack walking indeed [depends](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/de8045923ad2/src/share/vm/prims/forte.cpp#l127) on `MaxJavaStackTraceDepth`.

Since this is hard-coded in JVM, I can hardly do anything about it right now. So I'll just document the issue as you've suggested. The future plan is to get rid of AsyncGetCallTrace dependency at all (#66) - there are already too many problems with this API.

**Comment by artspb** [comment]
Thank you for addressing it so fast. And thank you for an amazing tool!
